<a href="https://colab.research.google.com/github/yubje/AI_Practice/blob/main/tensorflow101_%EC%83%9D%ED%99%9C%EC%BD%94%EB%94%A9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
# 라이브러리 사용
import pandas as pd
import tensorflow as tf

# 데이터 읽어오기 
file_route1 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/lemonade.csv'
lemonade = pd.read_csv(file_route1)

# 데이터 모양 확인
print(lemonade.shape)
print(iris.shape)
print()

# 데이터 열 이름 확인
print(lemonade.columns)
print(iris.columns)
print()

# 데이터 상위 5개 확인 
print(lemonade.head())


(6, 2)
(150, 5)

Index(['온도', '판매량'], dtype='object')
Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종'], dtype='object')

   온도  판매량
0  20   40
1  21   42
2  22   44
3  23   46
4  24   48

       nox  lstat  medv
0    0.538   4.98  24.0
1    0.469   9.14  21.6
2    0.469   4.03  34.7
3    0.458   2.94  33.4
4    0.458   5.33  36.2
..     ...    ...   ...
501  0.573   9.67  22.4
502  0.573   9.08  20.6
503  0.573   5.64  23.9
504  0.573   6.48  22.0
505  0.573   7.88  11.9

[506 rows x 3 columns]


# 레몬에이드 판매 예측

In [19]:
# 독립 변수와 종속 변수 분리 
independent = lemonade[['온도']]
dependent = lemonade[['판매량']]

print(independent)
print(dependent)

   온도
0  20
1  21
2  22
3  23
4  24
5  25
   판매량
0   40
1   42
2   44
3   46
4   48
5   50


In [20]:
# 모델의 구조를 만든다. 

# 독립변수의 개수 1개
X = tf.keras.layers.Input(shape=[1])
# 종속변수의 개수 1개 
Y = tf.keras.layers.Dense(1)(X)

# 독립변수, 종속변수
model = tf.keras.models.Model(X, Y)
# 컴파일 
model.compile(loss='mse')

## 모델 학습

### loss
- (예측 - 결과)^2

- 그 시점의 모델이 얼마나 정답에 가깝게 맞추고 있는지 평가하는 지표 

- 종속 변수와 예측 결과의 차이를 계산해서 그 값들의 평균을 구한 것

- loss가 0에 가까워질수록 정답에 가까움


### 진행 횟수
- Epoch 2/100 : 100회의 학습 중 2번째 학습

### 진행 속도
- 5ms/step : 한 회당 학습 속도

In [27]:
# 데이터로 모델을 학습(FIT)한다.
# epochs: 몇 번 학습할 것인지 입력
# verbose=0 : 화면 출력 X
model.fit(independent, dependent, epochs=990, verbose=0)
model.fit(independent, dependent, epochs=10)

Epoch 1/10
1/1 [==============================] - 0s 4ms/step - loss: 3.7990e-04
Epoch 2/10
1/1 [==============================] - 0s 8ms/step - loss: 3.7966e-04
Epoch 3/10
1/1 [==============================] - 0s 5ms/step - loss: 3.7948e-04
Epoch 4/10
1/1 [==============================] - 0s 6ms/step - loss: 3.7923e-04
Epoch 5/10
1/1 [==============================] - 0s 7ms/step - loss: 3.7909e-04
Epoch 6/10
1/1 [==============================] - 0s 5ms/step - loss: 3.7897e-04
Epoch 7/10
1/1 [==============================] - 0s 8ms/step - loss: 3.7879e-04
Epoch 8/10
1/1 [==============================] - 0s 8ms/step - loss: 3.7855e-04
Epoch 9/10
1/1 [==============================] - 0s 3ms/step - loss: 3.7833e-04
Epoch 10/10
1/1 [==============================] - 0s 7ms/step - loss: 3.7807e-04


In [28]:
# 모델을 이용한다
model.predict(independent)


array([[40.034195],
       [42.02566 ],
       [44.01713 ],
       [46.008602],
       [48.00007 ],
       [49.99154 ]], dtype=float32)

In [10]:
print("Predictions: ", model.predict([[15]]))

Predictions:  [[22.990213]]


# 보스턴 집값 예측

## 각 열 의미
- medv: 중간값(집값), 단위 $1000
- crim: 범죄율
- zn
- indus
- chas: 강변(charles river)
- nox
- rm: 평균 방 수
- age: 노후주택 비율
- dis 
- rad
- tax: 재산세 비율
- ptratio: 학생/교사 비율
- b
- lstat: 하위계층 비율 



In [11]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

# 1. 데이터 준비
file_route2 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
boston = pd.read_csv(file_route2)

# 1-1. 준비한 데이터 확인 
print("데이터 확인")
print(boston.shape)
print(boston.columns)
print(boston.head())

# 칼럼 선택하기
print(boston[['nox', 'lstat', 'medv']])

# 1-2. 독립변수, 종속변수 분리
independent = boston[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
            'ptratio', 'b', 'lstat']]
dependent = boston[['medv']]
print(independent.head())
print(dependent.head())

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')
      crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  medv
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]
      crim    zn  indus  chas    nox  ...  rad  tax  ptratio       b  lstat
0  0.00632  18.0   2.31     0  0.538  ...    1  296     15.3  396.90   4.98
1  0.02731   0.0   7.07     0  0.469  ...    2  242     17.8  396.90   9.14
2  0.02729   0.0   7.07     0  0.469  ...    2  242     17.8  392.83   4.03
3  0.03237   0.0   2.18     0  0.458  ...    3  222     18.7  394.63 

In [12]:
# 2. 모델의 구조를 만든다.
X = tf.keras.layers.Input(shape=[13])
Y = tf.keras.layers.Dense(1)(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [13]:
# 3. 데이터로 모델을 학습(FIT)한다.
model.fit(independent, dependent, epochs=3000, verbose=0)
model.fit(independent, dependent, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 1ms/step - loss: 24.7129
Epoch 2/10
16/16 [==============================] - 0s 1ms/step - loss: 24.3074
Epoch 3/10
16/16 [==============================] - 0s 1ms/step - loss: 24.6436
Epoch 4/10
16/16 [==============================] - 0s 1ms/step - loss: 24.3009
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 24.1158
Epoch 6/10
16/16 [==============================] - 0s 1ms/step - loss: 24.4076
Epoch 7/10
16/16 [==============================] - 0s 1ms/step - loss: 24.4788
Epoch 8/10
16/16 [==============================] - 0s 1ms/step - loss: 24.2878
Epoch 9/10
16/16 [==============================] - 0s 1ms/step - loss: 24.5246
Epoch 10/10
16/16 [==============================] - 0s 1ms/step - loss: 24.8525


In [ ]:
# 4. 모델을 이용한다. 
print(model.predict(independent[5:10]))
print(dependent[5:10])

[[25.410501]
 [21.91148 ]
 [18.94324 ]
 [10.783151]
 [18.288404]]
   medv
5  28.7
6  22.9
7  27.1
8  16.5
9  18.9


In [14]:
# 모델 수식 확인
print(model.get_weights())

[array([[-0.09305909],
       [ 0.05103278],
       [-0.03377039],
       [ 2.7598217 ],
       [ 0.84188527],
       [ 5.2734623 ],
       [-0.01026585],
       [-1.0052158 ],
       [ 0.1843835 ],
       [-0.01027561],
       [-0.4184661 ],
       [ 0.01428033],
       [-0.47133264]], dtype=float32), array([4.7189074], dtype=float32)]


house_price = -0.09296059 * x1 + 0.04728362 * x2 + -0.0201432 * x3 + ...


# 아이리스 품종 분류
- 범주형 데이터
- 분류(Classification)

In [ ]:
# 1. 데이터 가져오기
# 라이브러리 사용
import pandas as pd

# 데이터 읽어오기 

file_route3 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(file_route3)

# 데이터 모양 확인
print(iris.shape)

# 데이터 열 이름 확인
print(iris.columns)

# 데이터 상위 5개 확인 
print(iris.head())

# onehot-encoding: 품종(setosa, virginica, versicolor) => '품종_setosa', '품종_versicolor', '품종_virginica'
iris = pd.get_dummies(iris)





independent = iris[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
dependent = iris[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(independent.head())
print(dependent.shape)

   꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭
0   5.1  3.5    1.4   0.2
1   4.9  3.0    1.4   0.2
2   4.7  3.2    1.3   0.2
3   4.6  3.1    1.5   0.2
4   5.0  3.6    1.4   0.2
(150, 3)


In [ ]:
# 2. 모델의 구조를 만든다.
X = tf.keras.layers.Input(shape=[4])

# Activation함수(활성화 함수)
# sigmoid, softmax: 특정 결과가 나올 확률을 수치로 도출 
# softmax: 0과 1 사이의 결과값으로 나옴 
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
model = tf.keras.models.Model(X, Y)
# categorical_crossentropy로 계산된 차이값
# accyracy를 같이 보여줌 
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [ ]:
# 3. 데이터로 모델을 학습(Fit)합니다.
model.fit(independent, dependent, epochs=1000, verbose=0)
model.fit(independent, dependent, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1640 - accuracy: 0.9733
Epoch 2/10
5/5 [==============================] - 0s 1ms/step - loss: 0.1639 - accuracy: 0.9733
Epoch 3/10
5/5 [==============================] - 0s 1ms/step - loss: 0.1634 - accuracy: 0.9733
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1638 - accuracy: 0.9800
Epoch 5/10
5/5 [==============================] - 0s 1ms/step - loss: 0.1630 - accuracy: 0.9733
Epoch 6/10
5/5 [==============================] - 0s 1ms/step - loss: 0.1631 - accuracy: 0.9733
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1639 - accuracy: 0.9733
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1632 - accuracy: 0.9800
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1626 - accuracy: 0.9733
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1625 - accuracy: 0.9800


In [ ]:
# 4. 모델을 이용한다.
# 첫 데이터 5개
print(model.predict(independent[:5]))
print(dependent[:5])

print()
# 마지막 데이터 5개
print(model.predict(independent[-5:]))
print(dependent[-5:])

[[9.9917406e-01 8.2578720e-04 6.1443565e-08]
 [9.9729484e-01 2.7046339e-03 5.2496580e-07]
 [9.9837565e-01 1.6240928e-03 2.1870348e-07]
 [9.9560285e-01 4.3961853e-03 9.9022327e-07]
 [9.9923921e-01 7.6082471e-04 5.0672131e-08]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0

[[4.8320834e-07 1.3877459e-01 8.6122489e-01]
 [1.2641316e-06 1.8540102e-01 8.1459767e-01]
 [1.9838249e-06 2.5119054e-01 7.4880743e-01]
 [3.2583685e-07 1.5083568e-01 8.4916395e-01]
 [3.7356831e-06 3.2534212e-01 6.7465419e-01]]
     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [ ]:
# weights & bias 출력
print(model.get_weights())

[array([[ 1.3729701 ,  0.2611539 , -0.31711322],
       [ 2.2308123 ,  0.29900244, -1.3873504 ],
       [-3.9313948 , -0.4603671 ,  0.979452  ],
       [-4.329924  , -0.85880154,  1.9708254 ]], dtype=float32), array([ 1.6765242,  1.4561107, -1.7801377], dtype=float32)]
